sonar.projectKey=LedgerHQ_lumen
sonar.projectName=lumen
sonar.organization=ledger
sonar.sourceEncoding=UTF-8

sonar.sources=libs/ui-react/src,libs/ui-rnative/src,libs/utils-shared/src,libs/design-core/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.stories.tsx,**/*.mdx,**/*.figma.tsx,**/__mocks__/**,**/__tests__/**,**/test-setup.ts,**/jest.setup.ts,**/Symbols/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.cpd.exclusions=libs/ui-rnative/**

sonar.coverage.exclusions=**/*.tsx,**/*.test.ts,**/*.test.tsx,**/Symbols/**

sonar.javascript.lcov.reportPaths=libs/ui-react/test-output/vitest/coverage/lcov.info,libs/ui-rnative/test-output/jest/coverage/lcov.info,libs/utils-shared/test-output/vitest/coverage/lcov.info,libs/design-core/test-output/vitest/coverage/lcov.info

sonar.typescript.tsconfigPaths=tsconfig.base.json
sonar.javascript.node.maxspace=4096

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.newCode.referenceBranch=main
