export const DEFAULT_OFFSET = 10;
export const PADDING_X = 8;
export const PADDING_Y = 8;
export const ROW_HEIGHT = 16;
export const ROW_GAP = 4;
export const TITLE_GAP = 6;
export const TOOLTIP_TRANSITION = 'opacity 0.15s ease-out 0.05s';
export const LABEL_VALUE_GAP = 12;
export const DEFAULT_TOOLTIP_MIN_WIDTH = 80;
